/* tslint:disable */
/* eslint-disable */
/**
 * Open SB Career Website Admin API
 * <b>Quy trình các bước thực hiện sinh token để sử dụng Opent API:</b><br>Bước 1: Sinh token bằng api Login và sao chép kết quả token đoạn mã api trả ra<br>Bước 2: Xác thực Authorize bằng mã token đã sao chép bằng nút Authorize<br>Bước 3: Thực hiện gọi các api <br>----------------------------------------------------------------------
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

